name: Update resume.json

on: push

jobs:
  update-resume-gistt:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    
    - name: Deploy to Gist
      uses: exuanbo/actions-deploy-gist@v1.1.4
      with:
        # Set personal access token for updating gist.
        token: ${{ secrets.TOKEN }}
        # Set id of the gist to be updated.
        gist_id: da014a82b8da7e5f112d90c54157f496
        # Set description of the gist.
        gist_description: test description
        # Set file name in the gist.
        gist_file_name: resume.json
        # Set path of the file to be deployed.
        file_path: resume.json
        # Set file type of the file to be deployed.
        file_type: # optional, default is text
          
